//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PngtoFshBatchtxt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PngtoFshBatchtxt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files to the existing list.
        /// </summary>
        internal static string addBtn_ToolTip {
            get {
                return ResourceManager.GetString("addBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Alpha.
        /// </summary>
        internal static string AlphaGenString {
            get {
                return ResourceManager.GetString("AlphaGenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Transparency.
        /// </summary>
        internal static string AlphaTransString {
            get {
                return ResourceManager.GetString("AlphaTransString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        internal static string ArgumentDirectoryNotFound {
            get {
                return ResourceManager.GetString("ArgumentDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} path must not be empty..
        /// </summary>
        internal static string ArgumentPathEmpty {
            get {
                return ResourceManager.GetString("ArgumentPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate mipmaps for the zoom levels.
        /// </summary>
        internal static string autoProcMipsCb_ToolTip {
            get {
                return ResourceManager.GetString("autoProcMipsCb_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of images to convert. 
        ///Dragging files or folders onto the list will create a new list.
        /// </summary>
        internal static string batchListView_ToolTip {
            get {
                return ResourceManager.GetString("batchListView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Dat ({0} of {1}).
        /// </summary>
        internal static string BuildingDatStatusTextFormat {
            get {
                return ResourceManager.GetString("BuildingDatStatusTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress the items in the saved dat.
        /// </summary>
        internal static string compDatcb_ToolTip {
            get {
                return ResourceManager.GetString("compDatcb_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dat in Memory.
        /// </summary>
        internal static string DatInMemory {
            get {
                return ResourceManager.GetString("DatInMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found at {1}.
        /// </summary>
        internal static string FileNotFoundFormat {
            get {
                return ResourceManager.GetString("FileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the fsh type of the selected item.
        /// </summary>
        internal static string fshTypeBox_ToolTip {
            get {
                return ResourceManager.GetString("fshTypeBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fshwrite compression when saving DXT1 and DXT3 fsh images.
        /// </summary>
        internal static string fshWriteCompCb_ToolTip {
            get {
                return ResourceManager.GetString("fshWriteCompCb_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A processor that supports SSE is required to use FshWrite compression..
        /// </summary>
        internal static string FshWriteSSERequiredError {
            get {
                return ResourceManager.GetString("FshWriteSSERequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap files (*.png;*.bmp)|*.png;*.bmp|All files (*.*)|*.*.
        /// </summary>
        internal static string ImageFiles_Filter {
            get {
                return ResourceManager.GetString("ImageFiles_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the end diget of the instance id.
        /// </summary>
        internal static string InstanceIDRadioButtons_ToolTip {
            get {
                return ResourceManager.GetString("InstanceIDRadioButtons_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group id in Groupid.txt contains invalid characters. 
        ///It must only contain numbers 0-9 and letters A-F..
        /// </summary>
        internal static string InvalidGroupID {
            get {
                return ResourceManager.GetString("InvalidGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group id after /group: contains invalid characters.
        /// It must only contain numbers 0-9 and letters A-F..
        /// </summary>
        internal static string InvalidGroupIDArgument {
            get {
                return ResourceManager.GetString("InvalidGroupIDArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid instance..
        /// </summary>
        internal static string InvalidInstanceIDFormat {
            get {
                return ResourceManager.GetString("InvalidInstanceIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the format of the mipmaps..
        /// </summary>
        internal static string mipFormatCbo_Tooltip {
            get {
                return ResourceManager.GetString("mipFormatCbo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the output folder for the processed files.
        /// </summary>
        internal static string outFolderBtn_ToolTip {
            get {
                return ResourceManager.GetString("outFolderBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process the items in the list.
        /// </summary>
        internal static string processBatchBtn_ToolTip {
            get {
                return ResourceManager.GetString("processBatchBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Mipmaps ({0} of {1}).
        /// </summary>
        internal static string ProcessingMipsStatusTextFormat {
            get {
                return ResourceManager.GetString("ProcessingMipsStatusTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Image ({0} of {1}).
        /// </summary>
        internal static string ProcessingStatusTextFormat {
            get {
                return ResourceManager.GetString("ProcessingStatusTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Png to Fsh Batch.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected item from the list.
        /// </summary>
        internal static string remBtn_ToolTip {
            get {
                return ResourceManager.GetString("remBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process the list and save into a new dat.
        /// </summary>
        internal static string saveDatBtn_ToolTip {
            get {
                return ResourceManager.GetString("saveDatBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Dat.
        /// </summary>
        internal static string SavingDatStatusText {
            get {
                return ResourceManager.GetString("SavingDatStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Fsh ({0} of {1}).
        /// </summary>
        internal static string SavingFshProgressTextFormat {
            get {
                return ResourceManager.GetString("SavingFshProgressTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusTextReset {
            get {
                return ResourceManager.GetString("StatusTextReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the group id of the image.
        /// </summary>
        internal static string tgiGroupTxt_ToolTip {
            get {
                return ResourceManager.GetString("tgiGroupTxt_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the instance id of the image.
        /// </summary>
        internal static string tgiInstanceTxt_ToolTip {
            get {
                return ResourceManager.GetString("tgiInstanceTxt_ToolTip", resourceCulture);
            }
        }
    }
}
