//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PngtoFshBatchtxt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PngtoFshBatchtxt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Alpha.
        /// </summary>
        internal static string AlphaGenString {
            get {
                return ResourceManager.GetString("AlphaGenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Transparency.
        /// </summary>
        internal static string AlphaTransString {
            get {
                return ResourceManager.GetString("AlphaTransString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Dat ({0} of {1}).
        /// </summary>
        internal static string BuildingDatStatusTextFormat {
            get {
                return ResourceManager.GetString("BuildingDatStatusTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dat in Memory.
        /// </summary>
        internal static string DatInMemory {
            get {
                return ResourceManager.GetString("DatInMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A processor that supports SSE is required to for FshWrite save DXT1 and DXT3 fsh images.
        /// </summary>
        internal static string FshWriteSSERequiredError {
            get {
                return ResourceManager.GetString("FshWriteSSERequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Mipmaps ({0} of {1}).
        /// </summary>
        internal static string ProcessingMipsStatusTextFormat {
            get {
                return ResourceManager.GetString("ProcessingMipsStatusTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Image ({0} of {1}).
        /// </summary>
        internal static string ProcessingStatusTextFormat {
            get {
                return ResourceManager.GetString("ProcessingStatusTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Png to Fsh Batch.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Dat.
        /// </summary>
        internal static string SavingDatStatusText {
            get {
                return ResourceManager.GetString("SavingDatStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Fsh ({0} of {1}).
        /// </summary>
        internal static string SavingFshProgressTextFormat {
            get {
                return ResourceManager.GetString("SavingFshProgressTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusTextReset {
            get {
                return ResourceManager.GetString("StatusTextReset", resourceCulture);
            }
        }
    }
}
